name: Ed The Coder
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Build HTML
        run: |
          pip3 install -r requirements.txt
          make html

      - name: Deploy to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrest.REMOTE_HOST }}
          username: ${{ secrest.REMOTE_USER }}
          key: ${{ secrets.SSH_KEY }}
          passphrase: ${{ secrets.SSH_KEY_PASSPHRASE }}
          rm: true
          source: "output/"
          target: "${{ secrets.REMOTE_DIR }}"
